### ISSUE TITLE
[BUG] plot_series has side-effect on index name

### ISSUE THREAD

**Issue by aiwalter** [aeon-toolkit/aeon#1]
**Describe the bug**
Function `plot_series` has side-effects as `y` forgets index name after calling `plot_series`. Probably it can be fixed by simply adding a `y = y.copy()` to the function.

**To Reproduce**

```python
from sktime.datasets import load_airline
from sktime.utils.plotting import plot_series

y = load_airline()
y = y.to_frame()
y_name1 = y.index.name
plot_series(y)
y_name2 = y.index.name

assert y_name1 == y_name2
```
**Expected behavior**

**Additional context**

**Versions**
'0.15.0'

**Comment by GuiArcencio** [comment]
This might be a deeper problem than it looks. `plot_series` calls `check_Y` which in turn calls `check_series`, which has a `allow_index_names` parameter which defaults to `False` and is not changed. The issue seems to be that both `check` functions are not... functional. They both change their arguments as side-effects, instead of something like `y = check_Y(y)`
