### ISSUE TITLE
[ENH] Refactor `series_length` and `n_instances` to `n_timepoints` and `n_cases` in dictionary based classifiers

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#1151]
### Describe the feature or idea you want to propose

some time ago we agreed on calling the shape of collections of time series `(n_cases, n_channels, n_timepoints)`. Some classes still use `n_instances` and `series_length`, which is fine, but we would like to standardise.

For example, the dictionary based classifiers all use `n_instances` and `series_length` internally. 

### Describe your proposed solution

Following files contain `n_instances` and/or `series_length` . Refactor for `n_cases` and `n_timepoints`. Do one or more in one PR

- [ ] _boss.py
- [ ] _cboss.py
- [ ] _muse.py
- [ ] _weasel.py
- [ ] _tde.py
- [ ] _weasel_v2.py

**Comment by Vedant222** [comment]
Hi, I'm new to aeon and would like to start contributing with this issue.
To clarify, l should update the code so that the shapes of collections is internally represented as ```n_cases``` instead of ```n_instances``` and ```n_timepoints``` instead of ```series_length``` within the dictionary classifiers' files. This modification should also be reflected in the comments.

**Comment by baraline** [comment]
Hi @Vedant222 welcome to aeon ! 
You understood it right, the goal of this issue is to update the documentation related to the dictionnary based classifier. 

If you have any question about how to setup your dev environnement, the documentation should help you, otherwise you can ask any question on our Slack channel.
