### ISSUE TITLE
[MNT] Test `ElasticEnsemble` with all distances

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [aeon-toolkit/aeon#1499]
### Describe the issue

The EE classifier does not test with all distances according to the [coverage stats](https://app.codecov.io/gh/aeon-toolkit/aeon/blob/main/aeon%2Fclassification%2Fdistance_based%2F_elastic_ensemble.py#L141).

### Suggest a potential alternative/fix

Write a test in `test_elastic_ensemble.py` which ensures this works correctly. Other parameters can be tweaked to speed up the test if  necessary and it does not compromise the test output.

**Comment by CodeLionX** [comment]
Small addition: I guess the `all`-case should probably use `aeon.distances.get_distance_function_names()` instead of a hard-coded list of distances:

https://github.com/aeon-toolkit/aeon/blob/2dfca9caeeea3dfeced10d5c33acc25bbfcd6088/aeon/classification/distance_based/_elastic_ensemble.py#L140-L152

The only reason not to do this is incompatible distances, but I don't know if this is the case.

**Comment by itsdivya1309** [comment]
> Small addition: I guess the `all`-case should probably use `aeon.distances.get_distance_function_names()` instead of a hard-coded list of distances:
> 
> https://github.com/aeon-toolkit/aeon/blob/2dfca9caeeea3dfeced10d5c33acc25bbfcd6088/aeon/classification/distance_based/_elastic_ensemble.py#L140-L152
> 
> The only reason not to do this is incompatible distances, but I don't know if this is the case.

Hi!
I think the reason for not using `get_distance_function_names()` is that the list will be appended whenever a new distance function is implemented. Then, EE would need to be updated every time, as not all distance measures are used in EE.

**Comment by CodeLionX** [comment]
Ok, then ignore my comment 😉
