### ISSUE TITLE
[MNT] Similarity search and RDST test failures in CI

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [aeon-toolkit/aeon#2071]
### Describe the issue

Similarity search and RDST are currently causing some errors in CI:

https://github.com/aeon-toolkit/aeon/actions/runs/10826946884/job/30039020141
https://github.com/aeon-toolkit/aeon/actions/runs/10863339134/job/30147372111
https://github.com/aeon-toolkit/aeon/actions/runs/10890837654/job/30220422286
https://github.com/aeon-toolkit/aeon/actions/runs/10910622966/job/30281472461
https://github.com/aeon-toolkit/aeon/actions/runs/10918273185/job/30303353216 (other failure here as well)
https://github.com/aeon-toolkit/aeon/actions/runs/10918965119/job/30305612433

In case these expire, here are some examples:

```
FAILED aeon/testing/tests/test_all_estimators.py::test_all_estimators[check_fit_updates_state(estimator=RDSTRegressor(max_shapelets=20),datatype=EqualLengthUnivariate-Regression-np-list)] - ReferenceError: underlying object has vanished
```

```
FAILED aeon/similarity_search/distance_profiles/tests/test_naive_distance.py::test_normalized_naive_distance[dtw-float64] - ReferenceError: underlying object has vanished
```

I don't see any failures in `numba` disabled tests, but there is a low sample size.

### Suggest a potential alternative/fix

Solve the case of the missing underlying object.

### Additional context

Tests on general CI disabled by #2080

**Comment by baraline** [comment]
Summarizing what we discussed

Linked to this issue : https://github.com/numba/numba/issues/9348

The issue happens because of cache corruption on numba functions taking other numba function as parameter. 

Potential fixes in order of preference :
- Rework function so that it doesn't need the function argument
- Use a function checking for cache corruption as the one here https://github.com/ermshaua/claspy/blob/main/claspy/utils.py (numba_cache_safe) before calling these sensitive functions. Although using it inside numba function might not be possible. (Does the bug only happen when calling from python ?)
- Remove the function argument

**Comment by baraline** [comment]
Actions to fix RDST :
- [ ] Deprecate the distance argument to only use Manhattan, as in the paper. This argument also causes RDST to be a lot slower than expected. During this edit, replacing the `get_all_subsequences` to use strides would also improve scalability.

Actions to fix Similarity Search :
- [ ] Applying the cache corruption checking functions to the fetched distance functions in `naive_distance_profile.py` seems to be the simplest option.

**Comment by baraline** [comment]
Re-open and will close with the similarity search related PR
