### ISSUE TITLE
[ENH] Port in Kalman filters 

### ISSUE THREAD

**Issue by hadifawaz1999** [aeon-toolkit/aeon#375]
### Describe the feature or idea you want to propose

Because of non updated release of pykalman and is not supported in python 3.11 we can drop it and implement it ourselves

### Describe your proposed solution

Implement kalman filter

**Comment by hadifawaz1999** [comment]
Yeah this is why we removed the two naming `KalmanFilterTransformerPK` and `KalmanFilterTransformerFP` and just have one called `KalmanFilterTransformer` that uses `filterpy` which is a good solution for now, it works with python 3.11

**Comment by lmmentel** [comment]
We might be safe for some time since for now filterpy behaves well under py3.11. Long term it might cause problems since it doesn't  seem to be actively maintained. 

We could bring the relevant modules over at some point and commit to maintaining but it would be great to get a commitment from someone to own it before we do that.

**Comment by TonyBagnall** [comment]
#1669 removes the wrapper, if someone wants to port in best raise a new issue and this will confuse future us otherwise
