### ISSUE TITLE
[ENH] Adaptive linear segmentation algorithm

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#948]
### Describe the feature or idea you want to propose

It would be great to have an implementation of this piecewise linear approximation method for segmenting time series

https://ieeexplore.ieee.org/abstract/document/989531

### Describe your proposed solution

Implement as a base segmenter, internally store the fitted slopes

**Comment by Moonzyyy** [comment]
Will be taking doing this now!

**Comment by patrickzib** [comment]
This approach, in my assessment, does not fall under the category of segmentation algorithms such as "change point detection" or "semantic segmentation." Rather than being classified among segmentation techniques, it aligns more closely with data representation methods like Piecewise Aggregate Approximation (PAA), Symbolic Aggregate approXimation (SAX), or Symbolic Fourier Approximation (SFA). These methods focus on summarizing or approximating time series data rather than identifying distinct segments or change points within the data.
